artifacts:
  artifacts_root: ./artifacts

data_ingestion:
  root_dir: ./artifacts/data_ingestion
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data: ./artifacts/data_ingestion/data.zip
  unzip_dir: ./artifacts/data_ingestion
